### ISSUE TITLE
Incorrect cycle dataset link?

### ISSUE THREAD

**Issue by vijaydwivedi75** [cvignac/SMP#1]
Hi @cvignac,

Thanks for the open-source release of the code.

Can you please check the link for cycle detection dataset here? https://github.com/cvignac/SMP/blob/master/README.md#cycle-detection

It seems to be not working.

I get this message:

> This item might not exist or is no longer available
> This item might have been deleted, expired, or you might not have permission to view it. Contact the owner of this item for more information.

**Comment by cvignac** [comment]
Hello,
It seems that the link had expired. I replaced it by https://drive.switch.ch/index.php/s/nwbGJASmgYd0mU6

Clément

**Comment by vijaydwivedi75** [comment]
Thanks @cvignac!

**Comment by tuanle618** [comment]
Dear @cvignac,

apparently the link https://drive.switch.ch/index.php/s/nwbGJASmgYd0mU6 is not working anymore. 
I get the notification:
_File not found
The specified document has not been found on the server._

Could you kindly upload the file again?

Also tagging @vijaydwivedi75 , in case you could share with me the file otherwise.

Thanks!

**Comment by cvignac** [comment]
Hello,
I created a new link: https://drive.switch.ch/index.php/s/hv65hmY48GrRAoN

It seems that they expire after some time. If you know a way to share large files indefinitely, I am interested!
